### PR TITLE
Add `--[min/max]-created-time` to `az pipelines release list`

### PR DESCRIPTION
**Pull request by rmhartog**
Added the parameters `--min-created-time` and `--max-created-time` to `az pipelines release list`. Approach was so simple I decided to go ahead on the PR.

 - [x] : This PR has a corresponding issue open in the Repository. (#1343)
 - [x] : Approach is signed off on the issue.

### CODE REVIEW

**Review by v-soujanya — APPROVED** [review]

**Review by v-soujanya — COMMENTED** [review]
Hi @rmhartog we are going to publish the release, before that we need to test new functionality that is implemented here, kindly assist us with some test cases for this change, so that we can perform the testing before doing release

**Comment by v-soujanya** [comment]
Hi @rmhartog ! could you please assist us with test file/test cases regarding this change??

**Comment by rmhartog** [comment]
If the project you're testing with has at least three releases, you should be able to test using the following:

| Timestamp | Release      | Comment |
|------------|------------|-----------|
| `time_one`|Release one| |
| `time_two`|Release two| |
| `time_three`|Release three| |

Then you could have the following scenarios:
| `--min-created-time` | `--max-created-time` | Output |
| `time_one` | - | all three releases |
| `time_three` | - | only release three |
| - | `time_three` | all three releases |
| - | `time_one` | only release one |
| `time_one` | `time_two` | only release one and two |

Could you let me know what is feasible for your testing?

**Comment by v-soujanya** [comment]
Hi @rmhartog I have created few releases mentioned below, Please assist me to test the new parameters what is the value of min & max created time parameters?? may be if you have some live testing scenarios, please share screen shots with us. Thanks!
image

**Comment by v-soujanya** [comment]
> Hi @rmhartog I have created few releases mentioned below, Please assist me to test the new parameters what is the value of min & max created time parameters?? may be if you have some live testing scenarios, please share screen shots with us. Thanks! image

@rmhartog any update on this??

**Pull request merged**
