### PR TITLE
Resolving issues with merge and release pipeline failure

### PR DESCRIPTION
**Pull request by smunj**
Please make sure the code is following contribution guidelines in CONTRIBUTING.md

 - [ ] : This PR has a corresponding issue open in the Repository.
 - [ ] : Approach is signed off on the issue.

### CODE REVIEW

**Comment by ashishonce** [comment]
@narula0781 , this issue arise because of a breaking change in CLI master code.
https://github.com/Azure/azure-cli/commit/76742362fc9c44ca968859f748ec3bb594d75271
 this commit
I think we should be targeting a released version of CLI for which we are compliant, else these issues will come every time there is a breaking change. Thoughts?

**Comment by narula0781** [comment]
@ashishonce , @smunj - Lets discuss it once .

**Comment by KathrynEE** [comment]
@narula0781, @smunj, @ashishonce - What is happening with this PR? I'm waiting for resolution prior to closing this related github issue: https://github.com/MicrosoftDocs/azure-devops-docs/issues/8235.  Thanks.

**Comment by KathrynEE** [comment]
@narula0781, @smunj, @ashishonce - Can I get a response? What is happening with this PR? I'm waiting for resolution prior to closing this related github issue: [MicrosoftDocs/azure-devops-docs#8235](https://github.com/MicrosoftDocs/azure-devops-docs/issues/8235). Thanks.

**Comment by ashishonce** [comment]
Hi @KathrynEE , sorry missed this thread. This PR is no more valid as Azure CLI team fixed the breaking issue and now things are working fine. 
we can close this PR

**Pull request closed without merging**
