### PR TITLE
Added `--labels` parameter to `az repos pr create`

### PR DESCRIPTION
**Pull request by Apollo-Roboto**
Related issue: #1357

 - [X] : This PR has a corresponding issue open in the Repository.
 - [ ] : Approach is signed off on the issue.

---

This implementation of the --labels parameter works with space separated labels.
example:
```powershell
az repos pr create `
  --labels "documentation automated"
```

### CODE REVIEW

**Comment by florentvaldelievre** [comment]
Thanks for this PR. When can we expect an az cli release to include this feature?

**Comment by florentvaldelievre** [comment]
Thanks @v-anvashist . Do we have a rough timeline? We are wondering if we wait for a release or if we implement it using the Rest API

**Comment by v-anvashist** [comment]
Hi @florentvaldelievre  PM was OOF last week. We are checking the issue and I will confirm the timeline by tomorrow EOD.

**Comment by florentvaldelievre** [comment]
hi @v-anvashist Any updates please?

**Comment by v-anvashist** [comment]
Hi @florentvaldelievre By end of this week we are trying to publish the CLI release.

**Comment by florentvaldelievre** [comment]
@v-anvashist Im sorry to ask, but can I have an update please?

**Comment by v-anvashist** [comment]
Hi @florentvaldelievre No Problem !

PM is facing some access issues on github so we are not able to proceed further on this.

**Comment by florentvaldelievre** [comment]
Thank you for for the update
There hasn't been a CLI release for almost a year. It would be good to have a timeline for this please. Surely access issues should not take long to fix?

**Comment by v-anvashist** [comment]
For the reference I am sharing one PR here you can see some test file https://github.com/Azure/azure-devops-cli-extension/pull/1370/files#diff-01f7f33d0da0689e1f6c56cfec35bc91f4366265a256da16067b5396c3d64573

**Comment by v-anvashist** [comment]
Hi @florentvaldelievre  Do we have any updates on test file?

**Comment by florentvaldelievre** [comment]
@v-anvashist I am sorry, but I dont have the bandwidth to create tests.
The tests should be created by the developers who developed the feature.

**Pull request merged**
