### PR TITLE
1797650: Remove '?view=azure-cli-latest' syntax

### PR DESCRIPTION
**Pull request by jdmartinez36**
No code changes. Part of an effort to remove unnecessary versioning link syntax.

See user story [1797650](https://dev.azure.com/mseng/TechnicalContent/_workitems/edit/1797650) for more information.

### CODE REVIEW

**Review by dbradish-microsoft — APPROVED** [review]

**Comment by dbradish-microsoft** [comment]
@ashishonce, @narula0781, and/or @romil07, please approve the PR so we can sign off and bring closure to the cross-repo update of removing monikers that are for "latest".  Monikers should only be specified when we do NOT want the latest version.  Thanks very much!

**Comment by dbradish-microsoft** [comment]
#sign-off

These updates are being done in all MSFT repos containing Azure CLI links, and do not require author approval.

**Comment by dbradish-microsoft** [comment]
@ romil07 or @zhenghao104, could you please merge this PR?

**Comment by dbradish-microsoft** [comment]
@tedchamb, can you please merge this PR?  Thank you.

**Comment by dbradish-microsoft** [comment]
@chandrasekharmudili, can you please merge this PR?  Thank you.

**Comment by MightyPen** [comment]
I sent email to Ashish and Manish, asking them to Approve this PR #1073.

Thanks.
GeneMi (= MightyPen)

**Review by chandrasekharmudili — APPROVED** [review]

**Pull request merged**
