### PR TITLE
Set Required Reviewers on Pull Request

### PR DESCRIPTION
**Pull request by Apollo-Roboto**
Related issue: #1060

Please make sure the code is following contribution guidelines in CONTRIBUTING.md

 - [x] : This PR has a corresponding issue open in the Repository.
 - [ ] : Approach is signed off on the issue.

---

# az repos pr create
Added 2 new parameters `--required-reviewers` and `--optional-reviewers`. I kept the original `--reviewers` parameter which still adds optional reviewers.

If the same reviewer is added as both required and optional, it will only be set as required.

# az repos pr reviewers add
Added a new parameter `--required` that can make the list of reviewers being added required or optional.

---

Implementation wasn't too complicated since the azure-devops library already had support for the `is_required` field on the `IdentityRefWithVote` class.

### CODE REVIEW

**Comment by Apollo-Roboto** [comment]
hold on it broke

**Comment by luk355** [comment]
@v-anvashist, @V-hmusukula, any chance this PR can be reviewed and merged, please? I would also really welcome the fact that you can set the reviewer as Required.

**Comment by v-anvashist** [comment]
HI @luk355  I can see some conflicts in this PR.

**Comment by Apollo-Roboto** [comment]
I will take another look and fix the conflicts

**Comment by Apollo-Roboto** [comment]
I had to modify the implementation a little to fit with within the 20 branching limit from pylint. 
The checks have passed and it's now ready for review!

**Pull request merged**
