### PR TITLE
Fix incorrect Azure CLI reference links

### PR DESCRIPTION
**Pull request by dksimpson**
Bulk update: Edit incorrect Azure CLI reference links by removing /ext.

This work is in accordance with [User Story 1948095](https://dev.azure.com/mseng/TechnicalContent/_workitems/edit/1948095).

Please make sure the code is following contribution guidelines in CONTRIBUTING.md

 - [ ] : This PR has a corresponding issue open in the Repository.
 - [ ] : Approach is signed off on the issue.

### CODE REVIEW

**Comment by dksimpson** [comment]
#assign-reviewer @dbradish-microsoft

**Review by dbradish-microsoft — APPROVED** [review]

**Comment by dbradish-microsoft** [comment]
#sign-off with sufficient time given for ms.author review.

**Comment by dbradish-microsoft** [comment]
#sign-off with sufficient time given for ms.author review.

**Comment by dbradish-microsoft** [comment]
@v-anvashist, @V-hmusukula, Can you please merge this PR?  Thank you.

**Comment by dbradish-microsoft** [comment]
@v-anvashist, thanks a bunch!

**Pull request merged**
